using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// ï¿½Gï¿½~ï¿½bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ÌFï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½êŠ‡ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
/// </summary>
namespace StudioMaron
{
    [RequireComponent(typeof(LightFlashController))]
    public class EmissionColorController : MonoBehaviour
    {
        // Inspectorï¿½É•\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½Light Color Parameterï¿½Æ“ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        // ï¿½Â‚Ü‚è‚±ï¿½ÌƒRï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌƒCï¿½ï¿½ï¿½Xï¿½yï¿½Nï¿½^ï¿½Åİ’è‚·ï¿½ï¿½Ì‚Íï¿½ï¿½ï¿½ï¿½İ’ï¿½p
        [Header("-----Target Material--------------------------------------------------------------------------")]
        public List<Material> materialList = new List<Material>();

        [Header("-----Parameter--------------------------------------------------------------------------------")]
        public string shaderKeyWord = "_EmissionColor";
        public float baseIntensity = 1f;
        public LightColorParameter.GradientMode gradientMode;
        [GradientUsage(true)] public Gradient gradientColor;
        [Range(0, 1)] public float gradientValue = 0.5f;
        [Space(10)]

        [Header("-----Random Seed------------------------------------------------------------------------------")]
        public int randomSeed = 1234;
        [Space(10)]

        [Header("-----Option--------------------------------------------------------------------------")]
        // Timeline clipï¿½ï¿½ï¿½ï¿½Use Referenceï¿½AMix Referenceï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ê‡ï¿½Éİ’è‚·ï¿½ï¿½
        public LightColorReference reference;

        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½max60ï¿½É‚ï¿½ï¿½Ä•ï¿½ï¿½×‚ï¿½ï¿½ï¿½ï¿½ç‚·ï¿½pï¿½Ì•Ïï¿½
        float fps = 60;
        float deltaTime;
        int count;

        // Timelineï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ÌXï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
        bool parameterChangedByTimeline;

        // Light Color Parameterï¿½Ìƒï¿½ï¿½Xï¿½g
        // Timelineï¿½ï¿½ï¿½ç‚±ï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½AUpdateï¿½ï¿½ï¿½ÉŒvï¿½Zï¿½ï¿½ï¿½ï¿½
        [HideInInspector] public List<LightColorParameter> previousList = new List<LightColorParameter>();

        // ï¿½êï¿½ÉƒAï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Light Flash Controller(ï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ï¿½ï¿½Åï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½)
        [HideInInspector] public LightFlashController flashController;

        // ï¿½vï¿½Zï¿½pï¿½Ì•Ïï¿½
        float m_Intensity;
        float m_Value;
        Color m_Color;
        float m_CycleDuration;
        float m_CycleProgress;
        float r_Intensity;
        Color r_Color;
        float r_Weight;
        float x_Weight;
        float b_Intensity;

        // Startï¿½ï¿½ï¿½ï¿½Light Color Parameterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½
        private void Start()
        {
            CreateParameter();
        }
        // ï¿½ï¿½ï¿½Light Color Parameterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Inspectorï¿½Ìï¿½ï¿½Ú‚ğ”½‰fï¿½ï¿½ï¿½ApreviousListï¿½É“ï¿½ï¿½ï¿½ï¿½
        void CreateParameter()
        {
            var param = new LightColorParameter();
            param.gradientMode = gradientMode;
            param.gradientColor = gradientColor;
            param.gradientValue = gradientValue;
            param.colorScrollBPM = 0;
            param.weight = 1;
            SetParameter(new List<LightColorParameter>() { param });
        }
        // Light Color Parameterï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ì¬ï¿½ï¿½ï¿½ï¿½
        void SetParameter(List<LightColorParameter> list)
        {
            previousList.Clear();
            previousList.AddRange(list);
        }
        // Inspectorï¿½Ìï¿½ï¿½lï¿½ï¿½ÒWï¿½ï¿½ï¿½ï¿½ï¿½çƒ‰ï¿½Cï¿½gï¿½É”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        void OnValidate()
        {
            CreateParameter();
            UpdateColor();
        }
        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½g60(1.6msï¿½ï¿½ï¿½ï¿½)ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
        void Update()
        {
            // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½g60ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
            deltaTime += Time.deltaTime;
            if (deltaTime < 1 / fps) return;

            count = (int)(deltaTime * fps);
            deltaTime -= count / fps;

            // Timelineï¿½É‚ï¿½ï¿½ÏXï¿½ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Aï¿½Oï¿½ï¿½gï¿½ï¿½ï¿½ï¿½LightColorParameterï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½iï¿½ß‚ÄÄ—ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½
            if (!parameterChangedByTimeline)
            {
                foreach (var o in previousList)
                    o.clipTime += count / fps;
            }
            parameterChangedByTimeline = false;

            // Colorï¿½ÌXï¿½V
            UpdateColor();
        }
        // Colorï¿½ÌXï¿½V
        void UpdateColor()
        {
            // Use Referenceï¿½ï¿½ï¿½[ï¿½hï¿½pï¿½ï¿½Weightï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
            r_Weight = 0;
            // Mix Referenceï¿½ï¿½ï¿½[ï¿½hï¿½pï¿½ï¿½Weightï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
            x_Weight = 0;

            // ï¿½ï¿½ï¿½ê‚©ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ï¿½Use Referenceï¿½ï¿½Mix Referenceï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÎAï¿½vï¿½Zï¿½pï¿½ï¿½Weightï¿½É’Ç‰ï¿½ï¿½ï¿½ï¿½ï¿½
            for (int j = 0; j < previousList.Count; j++)
            {
                if (previousList[j].operationMode == LightColorParameter.OperationMode.UseReference)
                {
                    r_Weight += previousList[j].weight;
                }
                if (previousList[j].operationMode == LightColorParameter.OperationMode.MixReference)
                {
                    x_Weight += previousList[j].mixWeight * previousList[j].weight;
                }
            }
            // ï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ÉFï¿½Æ‹ï¿½ï¿½xï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½Ä“Kï¿½p
            for (int i = 0; i < materialList.Count; i++)
            {
                if (materialList[i] == null) continue;

                // ï¿½vï¿½Zï¿½pï¿½Ì•Ïï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
                m_Intensity = 0f;
                m_Color = Color.black;

                // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½Æƒï¿½ï¿½Cï¿½gï¿½Ôï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ÄŒvï¿½Zï¿½ï¿½ï¿½Am_Intensityï¿½ï¿½m_Colorï¿½Éï¿½ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                CalcColor(previousList, i, ref m_Intensity, ref m_Color);

                // Referenceï¿½ÌŒvï¿½Zï¿½pï¿½Ì•Ïï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
                r_Intensity = 0f;
                r_Color = Color.black;

                // Use Referenceï¿½ï¿½Mix Referenceï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÎAReferenceï¿½Ìƒpï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½
                if ((r_Weight != 0) || (x_Weight != 0))
                {
                    if (reference != null)
                    {
                        CalcColor(reference.GetReferenceColorParameter(), i, ref r_Intensity, ref r_Color);
                    }
                }
                // Light Flash Controllerï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½Í‚ï¿½ï¿½ÌŒWï¿½ï¿½ï¿½ï¿½ï¿½|ï¿½ï¿½ï¿½ï¿½
                b_Intensity = 1;
                float flashIntensity = 1f;
                if (flashController != null)
                {
                    b_Intensity = flashController.IntensityCoef(i, materialList.Count);
                }
                else
                {
                    if (TryGetComponent(out flashController))
                    {
                        b_Intensity = flashController.IntensityCoef(i, materialList.Count);
                    }
                }

                // EmissionColorã«åæ˜ ï¼ˆflashIntensityã‚’æ–°ãŸã«è¿½åŠ ï¼‰
                materialList[i].SetColor(shaderKeyWord, baseIntensity * b_Intensity * flashIntensity * (m_Intensity * m_Color * (1 - x_Weight) + r_Intensity * r_Color * (x_Weight + r_Weight)));
            }
        }

        // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
        void CalcColor(List<LightColorParameter> paramList, int n, ref float Intensity, ref Color Color)
        {
            // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½Æ‚ÉŒWï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½oï¿½ï¿½ï¿½AIntensityï¿½ï¿½Colorï¿½É‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½
            for (int j = 0; j < paramList.Count; j++)
            {
                if (paramList[j] == null) continue;

                // Use Referenceï¿½Ìê‡ï¿½Í•Ê‚ÅŒvï¿½Zï¿½ï¿½ï¿½ï¿½Ì‚ÅÈ—ï¿½ï¿½ï¿½ï¿½ï¿½
                if (paramList[j].operationMode == LightColorParameter.OperationMode.UseReference) continue;

                // BPMï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½sï¿½xï¿½vï¿½Z
                if (paramList[j].colorScrollBPM == 0)
                {
                    m_CycleDuration = 0;
                    m_CycleProgress = 0;
                    m_Value = paramList[j].gradientValue;
                }
                else
                {
                    m_CycleDuration = 60f * paramList[j].colorScrollBeat / paramList[j].colorScrollBPM;

                    if (m_CycleDuration == 0)
                        m_CycleProgress = 0;
                    else
                        m_CycleProgress = (paramList[j].clipTime % m_CycleDuration) / m_CycleDuration;

                    // m_Valueï¿½ï¿½BPMï¿½iï¿½sï¿½xï¿½ï¿½\ï¿½ï¿½
                    m_Value = paramList[j].gradientValue + (paramList[j].reverseScroll ? 1 - m_CycleProgress : m_CycleProgress);
                }

                // Gradient Modeï¿½ï¿½ï¿½Æ‚ÉFï¿½ÌŠï¿½ï¿½è“–ï¿½ï¿½
                switch (paramList[j].gradientMode)
                {
                    case LightColorParameter.GradientMode.Line:
                        m_Value = frac(m_Value + 0.5f + (n + 0.5f) / materialList.Count);
                        break;
                    case LightColorParameter.GradientMode.Sync:
                        break;
                    case LightColorParameter.GradientMode.Random:
                        m_Value = frac(m_Value + RandomFloat(paramList[j].overrideRamdomSeed ? paramList[j].randomSeed + n : randomSeed + n));
                        break;
                }
 
                // Intensityï¿½ï¿½Colorï¿½É‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½
                Intensity += paramList[j].intensityMultiplier * paramList[j].gradientColor.Evaluate(m_Value).a * paramList[j].weight;
                Color += paramList[j].gradientColor.Evaluate(m_Value) * paramList[j].weight;
            }
        }
        // Timeline clipï¿½ï¿½ï¿½ç”­ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
        public void SetParameterFromTimeline(List<LightColorParameter> parameter)
        {
#if UNITY_EDITOR
            if (UnityEditor.EditorApplication.isPlaying)
            {
                SetParameter(parameter);
            }
            else
            {
                SetParameter(parameter);
                UpdateColor();
            }
#else
                SetParameter(parameter);
#endif
            // Timelineï¿½É‚ï¿½ï¿½Xï¿½Vï¿½tï¿½ï¿½ï¿½O
            parameterChangedByTimeline = true;
        }

        // Timelineï¿½Ìƒvï¿½ï¿½ï¿½rï¿½ï¿½ï¿½[ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        public void ReapplyParameter()
        {
#if UNITY_EDITOR
            if (!UnityEditor.EditorApplication.isPlaying)
            {
                CreateParameter();
                UpdateColor();
            }
#endif
        }

        /// <summary>
        /// ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        /// </summary>
        Vector2 st = new Vector2();
        float RandomFloat(int seed)
        {
            st = new Vector2(seed, seed);
            return frac(Mathf.Sin(Vector2.Dot(st, new Vector2(12.9898f, 78.233f))) * 43758.5453f);
        }
        float frac(float f)
        {
            return f - Mathf.Floor(f);
        }
    }
}
