using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// ï¿½ï¿½ï¿½[ï¿½rï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½Cï¿½gï¿½ÌŠpï¿½xï¿½ï¿½ï¿½êŠ‡ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
/// </summary>
namespace StudioMaron
{
    public class LightAngleController : MonoBehaviour
    {
        // Inspectorï¿½É•\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½Light Color Parameterï¿½Æ“ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        // ï¿½Â‚Ü‚è‚±ï¿½ÌƒRï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌƒCï¿½ï¿½ï¿½Xï¿½yï¿½Nï¿½^ï¿½Åİ’è‚·ï¿½ï¿½Ì‚Íï¿½ï¿½ï¿½ï¿½İ’ï¿½p
        // ï¿½Gï¿½fï¿½Bï¿½^ï¿½gï¿½ï¿½ï¿½ï¿½Operation Modeï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        public List<LightAngle> lightAngleList = new List<LightAngle>();
        public Transform lookAtTarget;

        [Header("-----Parameter--------------------------------------------------------------------------------")]
        [HideInInspector] public LightAngleParameter.OperationMode operationMode = LightAngleParameter.OperationMode.None;
        [Space(10)]

        [Header("-----All Fixed-----------------------------------------------------------------------------")]
        [HideInInspector] public bool isInstant = false;
        [HideInInspector] [Range(-90, 90)] public float allFixed_Tilt = 0;
        [HideInInspector] [Range(-180, 180)] public float allFixed_Pan = 0;
        [HideInInspector] [Range(0, 1)] public float allFixed_NoiseRange = 0f;
        [HideInInspector] [Range(0, 1)] public float allFixed_NoiseSpeed = 0f;
        [Space(10)]

        [Header("-----Line Fixed-----------------------------------------------------------------------------")]
        [HideInInspector] [Range(-90, 90)] public float lineFixed_Tilt = 0;
        [HideInInspector] public bool lineFixed_Asymmetry = false;
        [HideInInspector] public AnimationCurve lineFixed_TiltCurve = AnimationCurve.Linear(timeStart: 0f, valueStart: 0f, timeEnd: 1f, valueEnd: 1f);
        [Space(10)]
        [HideInInspector] [Range(-180, 180)] public float lineFixed_Pan = 0;
        [HideInInspector] [Range(0, 1)] public float lineFixed_NoiseRange = 0f;
        [HideInInspector] [Range(0, 1)] public float lineFixed_NoiseSpeed = 0f;
        [Space(10)]

        [Header("-----Random Fixed-----------------------------------------------------------------------------")]
        [HideInInspector] [Range(-90, 90)] public float randomFixed_MaxTilt = 90;
        [HideInInspector] [Range(-90, 90)] public float randomFixed_MinTilt = -90;
        [Space(10)]
        [HideInInspector] [Range(-180, 180)] public float randomFixed_MaxPan = 180;
        [HideInInspector] [Range(-180, 180)] public float randomFixed_MinPan = -180;
        [Space(10)]
        [HideInInspector] public int randomFixed_RandomSeed = 1234;
        [HideInInspector] [Range(0, 1)] public float randomFixed_NoiseRange = 0f;
        [HideInInspector] [Range(0, 1)] public float randomFixed_NoiseSpeed = 0f;
        [Space(10)]

        [Header("-----Rotaion-----------------------------------------------------------------------------")]
        [HideInInspector] [Range(0, 90)] public float rotation_Tilt = 15;
        [HideInInspector] [Min(0.001f)] public float rotation_CycleTime = 3;
        [HideInInspector] [Range(0, 1)] public float rotation_Sync = 0;
        [HideInInspector] [Range(0, 1)] public float rotation_ReverseRate = 0;
        [HideInInspector] public int rotation_RandomSeed = 1234;
        [Space(10)]

        [Header("-----Tilt Wave-----------------------------------------------------------------------------")]
        [HideInInspector] [Range(-90, 90)] public float tiltWave_MaxTilt = 30;
        [HideInInspector] [Range(-90, 90)] public float tiltWave_MinTilt = -30;
        [HideInInspector] [Min(0.001f)] public float tiltWave_CycleTime = 5;
        [HideInInspector] [Range(0, 1)] public float tiltWave_Sync = 0;
        [HideInInspector] [Range(-180, 180)] public float tiltWave_Pan = 0;
        [Space(10)]

        [Header("-----Search Light-----------------------------------------------------------------------------")]
        [HideInInspector] [Range(0.01f, 1)] public float searchLight_Range = 0.5f;
        [HideInInspector] [Range(0.01f, 1)] public float searchLight_Speed = 0.5f;
        [HideInInspector] public int searchLight_RandomSeed = 1234;
        [Space(10)]

        [Header("-----Look At Target-----------------------------------------------------------------------------")]
        [HideInInspector] public Vector3 lookAtTarget_LookAtWorldOffset = Vector3.zero;
        [HideInInspector] [Range(0, 1)] public float lookAtTarget_NoiseRange = 0f;
        [HideInInspector] [Range(0, 1)] public float lookAtTarget_NoiseSpeed = 0f;
        [Space(10)]

        [Header("-----Option-----------------------------------------------------------------------------")]
        // Timeline clipï¿½ï¿½ï¿½ï¿½Use Referenceï¿½AMix Referenceï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ê‡ï¿½Éİ’è‚·ï¿½ï¿½
        [HideInInspector] public LightAngleReference reference;
        [Space(10)]
        [HideInInspector] public int noiseRandomSeed = 1234;


        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½max60ï¿½É‚ï¿½ï¿½Ä•ï¿½ï¿½×‚ï¿½ï¿½ï¿½ï¿½ç‚·ï¿½pï¿½Ì•Ïï¿½
        float fps = 60;
        float deltaTime;
        int count;

        // Timelineï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ÌXï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
        bool parameterChangedByTimeline;

        // Light Angle Parameterï¿½Ìƒï¿½ï¿½Xï¿½g
        // Timelineï¿½ï¿½ï¿½ç‚±ï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½AUpdateï¿½ï¿½ï¿½ÉŒvï¿½Zï¿½ï¿½ï¿½ï¿½
        [HideInInspector] public List<LightAngleParameter> previousList = new List<LightAngleParameter>();

        // Light Angle Infoï¿½Ìƒï¿½ï¿½Xï¿½g
        // ï¿½ï¿½ï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½eLight Angleï¿½É‘ï¿½ï¿½ï¿½ALight Angleï¿½ï¿½ï¿½pï¿½xï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½
        List<LightAngleInfo> infoList = new List<LightAngleInfo>();
        List<LightAngleInfo> info;

        // ï¿½vï¿½Zï¿½pï¿½Ì•Ïï¿½
        float coef;
        float sign;
        float ref_weight;

        // Startï¿½ï¿½ï¿½ï¿½Light Color Parameterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½
        private void Start()
        {
            CreateParameter();
        }
        // ï¿½ï¿½ï¿½Light Color Parameterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Inspectorï¿½Ìï¿½ï¿½Ú‚ğ”½‰fï¿½ï¿½ï¿½ApreviousListï¿½É“ï¿½ï¿½ï¿½ï¿½
        void CreateParameter()
        {
            var param = new LightAngleParameter();
            param.weight = 1;
            param.clipTime = 0;
            param.operationMode = operationMode;

            param.isInstant = isInstant;
            param.allFixed_Pan = allFixed_Pan;
            param.allFixed_Tilt = allFixed_Tilt;
            param.allFixed_NoiseRange = allFixed_NoiseRange;
            param.allFixed_NoiseSpeed = allFixed_NoiseSpeed;

            param.lineFixed_Pan = lineFixed_Pan;
            param.lineFixed_Tilt = lineFixed_Tilt;
            param.lineFixed_TiltCurve = lineFixed_TiltCurve;
            param.lineFixed_Asymmetry = lineFixed_Asymmetry;
            param.lineFixed_NoiseRange = lineFixed_NoiseRange;
            param.lineFixed_NoiseSpeed = lineFixed_NoiseSpeed;

            param.randomFixed_MaxPan = randomFixed_MaxPan;
            param.randomFixed_MinPan = randomFixed_MinPan;
            param.randomFixed_MaxTilt = randomFixed_MaxTilt;
            param.randomFixed_MinTilt = randomFixed_MinTilt;
            param.randomFixed_RandomSeed = randomFixed_RandomSeed;
            param.randomFixed_NoiseRange = randomFixed_NoiseRange;
            param.randomFixed_NoiseSpeed = randomFixed_NoiseSpeed;

            param.rotation_Tilt = rotation_Tilt;
            param.rotation_CycleTime = rotation_CycleTime;
            param.rotation_Sync = rotation_Sync;
            param.rotation_ReverseRate = rotation_ReverseRate;
            param.rotation_RandomSeed = rotation_RandomSeed;

            param.tiltWave_MaxTilt = tiltWave_MaxTilt;
            param.tiltWave_MinTilt = tiltWave_MinTilt;
            param.tiltWave_CycleTime = tiltWave_CycleTime;
            param.tiltWave_Sync = tiltWave_Sync;
            param.tiltWave_Pan = tiltWave_Pan;

            param.searchLight_Range = searchLight_Range;
            param.searchLight_Speed = searchLight_Speed;
            param.searchLight_RandomSeed = searchLight_RandomSeed;

            param.lookAtTarget_LookAtWorldOffset = lookAtTarget_LookAtWorldOffset;
            param.lookAtTarget_NoiseRange = lookAtTarget_NoiseRange;
            param.lookAtTarget_NoiseSpeed = lookAtTarget_NoiseSpeed;

            param.noiseRandomSeed = noiseRandomSeed;

            SetParameter(new List<LightAngleParameter>() { param });
        }
        // Light Angle Parameterï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ì¬ï¿½ï¿½ï¿½ï¿½
        void SetParameter(List<LightAngleParameter> list)
        {
            previousList.Clear();
            previousList.AddRange(list);
        }
        // Inspectorï¿½Ìï¿½ï¿½lï¿½ï¿½ÒWï¿½ï¿½ï¿½ï¿½ï¿½çƒ‰ï¿½Cï¿½gï¿½É”ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        public void OnValidate()
        {
            CreateParameter();
            UpdateAngle();
        }
        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½g60(1.6msï¿½ï¿½ï¿½ï¿½)ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
        void Update()
        {
            // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½g60ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
            deltaTime += Time.deltaTime;
            if (deltaTime < 1 / fps) return;

            count = (int)(deltaTime * fps);
            deltaTime -= count / fps;

            // Timelineï¿½É‚ï¿½ï¿½ÏXï¿½ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Aï¿½Oï¿½ï¿½gï¿½ï¿½ï¿½ï¿½LightColorParameterï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½iï¿½ß‚ÄÄ—ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½
            if (!parameterChangedByTimeline)
            {
                foreach (var o in previousList)
                    o.clipTime += count / fps;
            }
            parameterChangedByTimeline = false;

            // Angleï¿½ÌXï¿½V
            UpdateAngle();
        }

        // Angleï¿½ÌXï¿½V
        void UpdateAngle()
        {
            // Use Referenceï¿½ï¿½ï¿½[ï¿½hï¿½pï¿½ï¿½Weightï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
            ref_weight = 0;

            // ï¿½ï¿½ï¿½ê‚©ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ï¿½Use Referenceï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÎAï¿½vï¿½Zï¿½pï¿½ï¿½Weightï¿½É’Ç‰ï¿½ï¿½ï¿½ï¿½ï¿½
            for (int j = 0; j < previousList.Count; j++)
            {
                if (previousList[j].operationMode == LightAngleParameter.OperationMode.UseReference)
                {
                    ref_weight += previousList[j].weight;
                }
            }

            // ï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ÉŠpï¿½xï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½infoListï¿½É“ï¿½ï¿½ï¿½ï¿½
            for (int i = 0; i < lightAngleList.Count; i++)
            {
                if (lightAngleList[i] == null) continue;

                // infoListï¿½ÌƒNï¿½ï¿½ï¿½A
                infoList.Clear();

                // Use Referenceï¿½ï¿½Mix Referenceï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÎAReferenceï¿½Ìƒpï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½infoListï¿½É“ï¿½ï¿½ï¿½ï¿½
                if (ref_weight != 0)
                {
                    if (reference != null)
                    {
                        infoList.AddRange(CalcAngle(reference.GetReferenceAngleParameter(), i, lightAngleList.Count, ref_weight));
                    }
                }

                // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ï¿½pï¿½xï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½infoListï¿½É“ï¿½ï¿½ï¿½ï¿½
                infoList.AddRange(CalcAngle(previousList, i, lightAngleList.Count));

                // ï¿½eLight Angleï¿½ï¿½infoListï¿½ğ‘—‚ï¿½
                lightAngleList[i].SetPanTiltSlerp(infoList);
            }
        }
        // ï¿½pï¿½xï¿½ÌŒvï¿½Z
        List<LightAngleInfo> CalcAngle(List<LightAngleParameter> paramList, int n, int length, float weightCoef = 1)
        {
            info = new List<LightAngleInfo>();

            // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½Æ‚ï¿½infoï¿½ï¿½ï¿½ï¿½ï¿½AinfoListï¿½É’Ç‰ï¿½ï¿½ï¿½ï¿½ï¿½
            for (int k = 0; k < paramList.Count; k++)
            {
                info.Add(new LightAngleInfo());
                info[k].weight = paramList[k].weight * weightCoef;
                info[k].noiseRandomSeed = paramList[k].noiseRandomSeed + n;

                // Operation Modeï¿½ï¿½ï¿½Æ‚Ìï¿½ï¿½ï¿½
                switch (paramList[k].operationMode)
                {
                    // Noneï¿½ï¿½ï¿½[ï¿½hï¿½Å‚ï¿½infoï¿½ğ–³Œï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
                    case LightAngleParameter.OperationMode.None:
                        info[k].isInvalid = true;
                        break;
                    // All Fixedï¿½ï¿½ï¿½[ï¿½hï¿½Í‘Sï¿½Ä‚Ìƒï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½x
                    case LightAngleParameter.OperationMode.All_Fixed:
                        info[k].pan = paramList[k].allFixed_Pan;
                        info[k].tilt = paramList[k].allFixed_Tilt;

                        info[k].noiseRange = paramList[k].allFixed_NoiseRange;
                        info[k].noiseSpeed = paramList[k].allFixed_NoiseSpeed;
                        break;
                    // Line Fixedï¿½ï¿½ï¿½[ï¿½hï¿½Å‚Íï¿½ï¿½Eï¿½ÎÌ‚ï¿½Vï¿½ï¿½ï¿½ÉŠpï¿½xï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½
                    case LightAngleParameter.OperationMode.Line_Fixed:

                        if(length <= 2)
                        {
                            if(n == 0)
                                coef = -1;
                            else
                                coef = 1;
                            info[k].pan = paramList[k].lineFixed_Pan * coef;

                            if (paramList[k].lineFixed_Asymmetry)
                                coef = paramList[k].lineFixed_TiltCurve.Evaluate(n / (length - 1f));
                            else
                                coef = paramList[k].lineFixed_TiltCurve.Evaluate(1);
                            info[k].tilt = paramList[k].lineFixed_Tilt * coef;
                        }
                        else
                        {
                            // Pan
                            // ï¿½zï¿½ï¿½Ì‘Oï¿½ï¿½
                            if (n < (length - 1) / 2f)
                                coef = -1 * (1 - n / ((length - 1) / 2f));
                            // ï¿½zï¿½ï¿½Ì^ï¿½ï¿½
                            else if (n == (length - 1) / 2f)
                                coef = 0;
                            // ï¿½zï¿½ï¿½ÌŒã”¼
                            else
                                coef = (n - (length - 1) / 2f) / ((length - 1) / 2f);

                            info[k].pan = paramList[k].lineFixed_Pan * coef;

                            // Tilt
                            // ï¿½ï¿½ï¿½Eï¿½ï¿½ÎÌ‚É‚ï¿½ï¿½ï¿½1ï¿½ï¿½É‚ï¿½ï¿½ï¿½ê‡
                            if (paramList[k].lineFixed_Asymmetry)
                                coef = paramList[k].lineFixed_TiltCurve.Evaluate(n / (length - 1f));
                            // ï¿½ï¿½ï¿½Eï¿½Îï¿½
                            else
                            {
                                // ï¿½zï¿½ñ‚ª‹ï¿½ï¿½ï¿½
                                if (length % 2 == 0)
                                {
                                    // ï¿½zï¿½ï¿½Ì‘Oï¿½ï¿½
                                    if (n < length / 2f)
                                        coef = paramList[k].lineFixed_TiltCurve.Evaluate(1 - n / ((length / 2f) - 1));
                                    // ï¿½zï¿½ï¿½ÌŒã”¼
                                    else
                                        coef = paramList[k].lineFixed_TiltCurve.Evaluate((n - (length / 2f)) / ((length / 2f) - 1));
                                }
                                // ï¿½zï¿½ñ‚ªŠï”
                                else
                                {
                                    // ï¿½zï¿½ï¿½Ì‘Oï¿½ï¿½
                                    if (n < (length - 1) / 2f)
                                        coef = paramList[k].lineFixed_TiltCurve.Evaluate(1 - n / ((length - 1) / 2f));
                                    // ï¿½zï¿½ï¿½Ì^ï¿½ï¿½
                                    else if (n == (length - 1) / 2f)
                                        coef = paramList[k].lineFixed_TiltCurve.Evaluate(0);
                                    // ï¿½zï¿½ï¿½ÌŒã”¼
                                    else
                                        coef = paramList[k].lineFixed_TiltCurve.Evaluate((n - (length - 1) / 2f) / ((length - 1) / 2f));
                                }
                            }
                            info[k].tilt = paramList[k].lineFixed_Tilt * coef;
                        }

                        info[k].noiseRange = paramList[k].lineFixed_NoiseRange;
                        info[k].noiseSpeed = paramList[k].lineFixed_NoiseSpeed;
                        break;
                    // Random Fixedï¿½ï¿½ï¿½[ï¿½hï¿½Å‚ÍƒVï¿½[ï¿½hï¿½lï¿½Å—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ÈŠpï¿½xï¿½Åƒï¿½ï¿½Cï¿½gï¿½ï¿½zï¿½uï¿½ï¿½ï¿½ï¿½
                    case LightAngleParameter.OperationMode.Random_Fixed:
                        coef = RandomFloat(paramList[k].randomFixed_RandomSeed + n);
                        info[k].pan = Mathf.Lerp(paramList[k].randomFixed_MinPan, paramList[k].randomFixed_MaxPan, coef);
                        coef = RandomFloat(paramList[k].randomFixed_RandomSeed * 2 + n);
                        info[k].tilt = Mathf.Lerp(paramList[k].randomFixed_MinTilt, paramList[k].randomFixed_MaxTilt, coef);

                        info[k].noiseRange = paramList[k].randomFixed_NoiseRange;
                        info[k].noiseSpeed = paramList[k].randomFixed_NoiseSpeed;
                        break;
                    // Rotationï¿½ï¿½ï¿½[ï¿½hï¿½Íˆï¿½ï¿½ï¿½Tiltï¿½pï¿½ÅƒOï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½
                    case LightAngleParameter.OperationMode.Rotation:
                        coef = RandomFloat(paramList[k].rotation_RandomSeed + n) * (1 - paramList[k].rotation_Sync);
                        sign = RandomFloat(paramList[k].rotation_RandomSeed + n) < paramList[k].rotation_ReverseRate ? -1 : 1;
                        info[k].pan = 360 * frac((Time.time / paramList[k].rotation_CycleTime) + coef) * sign;
                        info[k].tilt = paramList[k].rotation_Tilt;
                        break;
                    // Tilt Waveï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½Tiltï¿½Ìã‚°ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½v
                    case LightAngleParameter.OperationMode.Tilt_Wave:
                        // Pan
                        // ï¿½zï¿½ï¿½Ì‘Oï¿½ï¿½
                        if (n < (length - 1) / 2f)
                        {
                            coef = -1 * (1 - n / ((length - 1) / 2f));
                        }
                        // ï¿½zï¿½ï¿½Ì^ï¿½ï¿½
                        else if (n == (length - 1) / 2f)
                        {
                            coef = 0;
                        }
                        // ï¿½zï¿½ï¿½ÌŒã”¼
                        else
                        {
                            coef = (n - (length - 1) / 2f) / ((length - 1) / 2f);
                        }
                        info[k].pan = paramList[k].tiltWave_Pan * coef;

                        // Tilt
                        coef = Mathf.Sin(2 * Mathf.PI * Time.time / paramList[k].tiltWave_CycleTime - (2 * Mathf.PI * n / length) * (1 - paramList[k].tiltWave_Sync));
                        info[k].tilt = (paramList[k].tiltWave_MaxTilt + paramList[k].tiltWave_MinTilt) * 0.5f + (paramList[k].tiltWave_MaxTilt - paramList[k].tiltWave_MinTilt) * 0.5f * coef;
                        break;
                    // Search Lightï¿½ï¿½ï¿½[ï¿½hï¿½ÍƒTï¿½[ï¿½`ï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½Û‚ï¿½ï¿½ï¿½ï¿½ï¿½
                    case LightAngleParameter.OperationMode.Search_Light:
                        // Pan
                        coef = RandomFloat(paramList[k].searchLight_RandomSeed + n);
                        sign = RandomFloat(paramList[k].searchLight_RandomSeed + n) < 0.5f ? -1 : 1;
                        info[k].pan = 360 * frac((Time.time * paramList[k].searchLight_Speed * 0.25f) + coef) * sign;

                        // Tilt
                        coef = Mathf.Sin(2 * Mathf.PI * Time.time * paramList[k].searchLight_Speed * 0.63f - (2 * Mathf.PI * n / length));
                        info[k].tilt = paramList[k].searchLight_Range * 60 * coef;

                        break;
                    // Look At Target
                    case LightAngleParameter.OperationMode.LookAt_Target:
                        if (lookAtTarget != null)
                        {
                            info[k].isLookAtTarget = true;
                            info[k].targetPosition = lookAtTarget.position + paramList[k].lookAtTarget_LookAtWorldOffset;
                            info[k].noiseRange = paramList[k].lookAtTarget_NoiseRange;
                            info[k].noiseSpeed = paramList[k].lookAtTarget_NoiseSpeed;
                        }
                        else
                            info[k].isInvalid = true;
                        break;
                    // Use Referenceï¿½ï¿½Referenceï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½Æ‚ï¿½ï¿½ï¿½Bï¿½ï¿½ï¿½ï¿½ï¿½ÌƒVï¿½[ï¿½hï¿½lï¿½ï¿½Referenceï¿½Æ“ï¿½ï¿½ï¿½ï¿½É‚È‚é‚±ï¿½Æ‚É’ï¿½ï¿½ï¿½
                    case LightAngleParameter.OperationMode.UseReference:
                        info[k].isInvalid = true;
                        break;
                }
            }
            return info;
        }

        // Timeline clipï¿½ï¿½ï¿½ç”­ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
        public void SetParameterFromTimeline(List<LightAngleParameter> parameter)
        {
#if UNITY_EDITOR
            if (UnityEditor.EditorApplication.isPlaying)
            {
                SetParameter(parameter);
            }
            else
            {
                SetParameter(parameter);
                UpdateAngle();
            }
#else
                SetParameter(parameter);
#endif
        }
        // Timelineï¿½Ìƒvï¿½ï¿½ï¿½rï¿½ï¿½ï¿½[ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        public void ReapplyParameter()
        {
#if UNITY_EDITOR
            if (!UnityEditor.EditorApplication.isPlaying)
            {
                CreateParameter();
                UpdateAngle();
            }
#endif
        }
        /// <summary>
        /// ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        /// </summary>
        Vector2 st = new Vector2();
        float RandomFloat(int seed)
        {
            st = new Vector2(seed, seed);
            return frac(Mathf.Sin(Vector2.Dot(st, new Vector2(12.9898f, 78.233f))) * 43758.5453f);
        }
        float frac(float f)
        {
            return f - Mathf.Floor(f);
        }

        // ï¿½qï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½Light Angleï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äæ“¾ï¿½ï¿½ï¿½ï¿½
        // Inspectorï¿½Ì‰Eï¿½ã‚©ï¿½ç”­ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½
        [ContextMenu("Get LightAngle component from children")]
        public void GetLightListFromChildren()
        {
            var array = GetComponentsInChildren<LightAngle>();
            if (array.Length == 0) return;

            var list = new List<LightAngle>(array);

            lightAngleList.Clear();
            lightAngleList.AddRange(list);
        }

    }
}
