using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// ï¿½ï¿½ï¿½[ï¿½rï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½Cï¿½gï¿½Ìï¿½ï¿½ï¿½
/// </summary>
namespace StudioMaron
{
    public class LightAngle : MonoBehaviour
    {
        public enum Axis
        {
            X,
            Y,
            Z
        }

        [Header("-----Tilt-------------------------------------------------------------------------------")]
        public Transform tilt;
        // Tiltï¿½Å‰ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½ï¿½
        public Axis rotAxis_Tilt = Axis.X;
        // Tiltï¿½Ìƒï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½ï¿½]ï¿½Ìï¿½ï¿½ï¿½ï¿½l
        public Vector3 initRot_Tilt;
        [Space(10)]
        public bool debugTilt;
        [Range(-90, 90)] public float debugTiltAngle;

        [Header("-----Pan--------------------------------------------------------------------------------")]
        public Transform pan;
        // Panï¿½Å‰ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½ï¿½
        public Axis rotAxis_Pan = Axis.Y;
        // Panï¿½Ìƒï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½ï¿½]ï¿½Ìï¿½ï¿½ï¿½ï¿½l
        public Vector3 initRot_Pan;
        [Space(10)]
        public bool debugPan;
        [Range(-180, 180)] public float debugPanAngle;

        [Header("-----Look At Target--------------------------------------------------------------------------------")]
        // Look at targetï¿½pï¿½ï¿½Tiltï¿½Ìï¿½ï¿½ï¿½ï¿½í‚¹ï¿½B[X,Y,Z,-X,-Y,-Z]ï¿½ï¿½6ï¿½pï¿½^ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½1ï¿½Â‘Iï¿½ï¿½
        [Range(0, 5)] public int lookAtAxisAdjust_Tilt;
        // Look at targetï¿½pï¿½ï¿½Panï¿½Ìï¿½ï¿½ï¿½ï¿½í‚¹ï¿½B[X,Y,Z]ï¿½~[Y,Z,-Y,-Z]ï¿½ï¿½12ï¿½pï¿½^ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½1ï¿½Â‘Iï¿½ï¿½
        [Range(0, 11)] public int lookAtAxisAdjust_Pan;
        [Space(10)]
        // ï¿½ï¿½Lï¿½Ìï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‚É‚Â‚ï¿½ï¿½ï¿½ï¿½Bï¿½^ï¿½[ï¿½Qï¿½bï¿½gï¿½Ì•ï¿½ï¿½ï¿½ï¿½ğ³‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½Iï¿½ÔB
        public bool debugLookAt;
        public Transform debugLookAtTarget;

        // ï¿½vï¿½Zï¿½pï¿½Ì•Ïï¿½
        Quaternion init;
        Quaternion end;
        float noisePan;
        float noiseTilt;
        Vector3 noisePosition;
        float weight;
        bool invalid;
        List<LightAngleInfo> infoList = new List<LightAngleInfo>();
        Quaternion previousWorldRot_Pan = Quaternion.identity;
        Quaternion previousWorldRot_Tilt = Quaternion.identity;
        Quaternion previousLocalRot_Pan = Quaternion.identity;
        Quaternion previousLocalRot_Tilt = Quaternion.identity;

        // Inspectorï¿½Ìï¿½ï¿½lï¿½Ì•ÏXï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        private void OnValidate()
        {
            infoList.Clear();

            var info = new LightAngleInfo();

            // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½[ï¿½hï¿½Ìê‡ï¿½AInspectorï¿½ÌŠpï¿½xï¿½ğ”½‰fï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            info.pan = debugPanAngle;
            info.tilt = debugTiltAngle;
            info.weight = 1;
            if (debugLookAt && debugLookAtTarget)
            {
                info.isLookAtTarget = true;
                info.targetPosition = debugLookAtTarget.position;
            }
            infoList.Add(info);

            // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½Panï¿½ï¿½Tiltï¿½ï¿½Kï¿½pï¿½ï¿½ï¿½ï¿½
            SetPanTiltSlerp(infoList, true);
        }
        // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½[ï¿½hï¿½Ìê‡ï¿½Ì‚ï¿½Updateï¿½ÅŒvï¿½Zï¿½ï¿½ï¿½ï¿½Bï¿½Êï¿½ï¿½Light Angle Controllerï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½Ò‚ï¿½
        private void Update()
        {
            if (debugTilt || debugPan || debugLookAt)
                OnValidate();
        }
        // Light Angle Controllerï¿½ï¿½ï¿½ç”­ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½BisDebugModeï¿½ï¿½ï¿½Æ‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½fï¿½ï¿½ï¿½é‚ªï¿½Aï¿½Êï¿½ï¿½Slerp(previous, current, 0.1f)ï¿½Åƒï¿½ï¿½[ï¿½pï¿½Xï¿½tï¿½Bï¿½ï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        public void SetPanTiltSlerp(List<LightAngleInfo> infoList, bool isDebugMode = false)
        {
            // infoListï¿½Ì’ï¿½ï¿½gï¿½ï¿½ï¿½Sï¿½Ä–ï¿½ï¿½ï¿½ï¿½È‚çˆï¿½ï¿½ï¿½Iï¿½ï¿½
            invalid = true;
            for (int i = 0; i < infoList.Count; i++)
            {
                invalid = invalid && infoList[i].isInvalid;
            }
            if (invalid) return;

            weight = 0;

            if (isDebugMode)
            {
                // ï¿½fï¿½oï¿½bï¿½Oï¿½ï¿½ï¿½[ï¿½hï¿½Ìê‡ï¿½ï¿½Tiltï¿½ï¿½Panï¿½ï¿½Ğ•ï¿½ï¿½ï¿½ï¿½Â“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Å‰ï¿½]ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                if (debugPan)
                    pan.localRotation = Quaternion.identity;
                if(debugTilt)
                    tilt.localRotation = Quaternion.identity;
                if (debugLookAt)
                {
                    pan.localRotation = Quaternion.identity;
                    tilt.localRotation = Quaternion.identity;
                }
            }
            else
            {
                // ï¿½ï¿½]ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Bï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Look At Targetï¿½Ìï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½Ì‚É•Kï¿½v
                pan.localRotation = Quaternion.identity;
                tilt.localRotation = Quaternion.identity;
            }

            for (int i = 0; i < infoList.Count; i++)
            {
                if (infoList[i].isInvalid) continue;
                if (infoList[i].weight == 0) continue;
                // Look At Targetï¿½Ìï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ÍƒOï¿½ï¿½ï¿½[ï¿½oï¿½ï¿½ï¿½ï¿½]ï¿½ÅŒvï¿½Zï¿½ï¿½ï¿½ï¿½Kï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B
                if (infoList[i].isLookAtTarget)
                {
                    if (pan == null) continue;
                    if (tilt == null) continue;

                    weight += infoList[i].weight;
                    noisePan = infoList[i].noiseRange * (-2 + 4 * perlinNoise(new Vector2(RandomFloat(infoList[i].noiseRandomSeed), Time.time * infoList[i].noiseSpeed * 3 - infoList[i].noiseRandomSeed)));
                    noiseTilt = infoList[i].noiseRange * (-2 + 4 * perlinNoise(new Vector2(RandomFloat(2 * infoList[i].noiseRandomSeed), Time.time * infoList[i].noiseSpeed * 3 + infoList[i].noiseRandomSeed)));
                    noisePosition = new Vector3(noisePan, 0, noiseTilt);

                    // Pan
                    init = Quaternion.Euler(initRot_Pan);

                    var pan_up = AxisAdjustPan(Dir.UP, lookAtAxisAdjust_Pan, pan);
                    var pan_forward = AxisAdjustPan(Dir.FORWARD, lookAtAxisAdjust_Pan, pan);

                    var panToTarget = infoList[i].targetPosition - pan.position - noisePosition;
                    var projection_p = panToTarget - Vector3.Dot(panToTarget, pan_up) * pan_up;
                    var angle_p = Vector3.Angle(pan_forward, projection_p);
                    if (angle_p < 179)
                        infoList[i].quaternion = Quaternion.FromToRotation(pan_forward, projection_p) * pan.rotation * init;
                    else
                        infoList[i].quaternion = Quaternion.AngleAxis(angle_p, pan_up) * pan.rotation * init; // since the object flips around 180 degrees.

                    end = Quaternion.Slerp(pan.rotation, infoList[i].quaternion, infoList[i].weight / weight);
                    pan.rotation = infoList[i].quaternion;
                    if (weight == 1)
                    {
                        previousLocalRot_Pan = pan.localRotation;
                        previousWorldRot_Pan = pan.rotation;
                    }

                    // Tilt
                    init = Quaternion.Euler(initRot_Tilt);

                    var tilt_up = AxisAdjustTilt(Dir.UP, lookAtAxisAdjust_Tilt, tilt); // Tiltï¿½ï¿½UPï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Î‚æ‚¢

                    var tiltToTarget = infoList[i].targetPosition - tilt.position - noisePosition;
                    var projection_t = tiltToTarget; // Panï¿½ÅŠï¿½ï¿½ÉŒï¿½ï¿½ï¿½ï¿½Ì’ï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ì‚Åuï¿½Vï¿½ï¿½ï¿½~ï¿½bï¿½gï¿½Ìï¿½ï¿½Kï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rightï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìíœï¿½vï¿½Ì‘ï¿½ï¿½ï¿½Í•sï¿½v
                    infoList[i].quaternion = Quaternion.FromToRotation(tilt_up, projection_t) * tilt.rotation * init;

                    end = Quaternion.Slerp(tilt.rotation, infoList[i].quaternion, infoList[i].weight / weight);
                    tilt.rotation = infoList[i].quaternion;
                    if (weight == 1)
                    {
                        previousLocalRot_Tilt = tilt.localRotation;
                        previousWorldRot_Tilt = tilt.rotation;
                    }
                }
                // Look At Targetï¿½ÈŠOï¿½Ìï¿½ï¿½ï¿½ï¿½Íƒï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½ï¿½]ï¿½Åsï¿½ï¿½
                else
                {
                    weight += infoList[i].weight;
                    if (pan != null)
                    {
                        init = Quaternion.Euler(initRot_Pan);
                        noisePan = infoList[i].noiseRange * (-180 + 360 * perlinNoise(new Vector2(RandomFloat(infoList[i].noiseRandomSeed), Time.time * infoList[i].noiseSpeed * 3 - infoList[i].noiseRandomSeed)));
                        infoList[i].quaternion = Q_Axis(rotAxis_Pan, infoList[i].pan + noisePan) * init;
                        end = Quaternion.Slerp(pan.localRotation, infoList[i].quaternion, infoList[i].weight / weight);
                        if (isDebugMode)
                        {
                            if(debugPan)
                                pan.localRotation = end;
                        }
                        else
                        {
                            pan.localRotation = infoList[i].quaternion;
                        }
                        if (weight == 1)
                        {
                            previousLocalRot_Pan = pan.localRotation;
                            previousWorldRot_Pan = pan.rotation;
                        }
                    }

                    if (tilt != null)
                    {
                        init = Quaternion.Euler(initRot_Tilt);
                        noiseTilt = infoList[i].noiseRange * (-45 + 90 * perlinNoise(new Vector2(RandomFloat(2 * infoList[i].noiseRandomSeed), Time.time * infoList[i].noiseSpeed * 3 + infoList[i].noiseRandomSeed)));
                        infoList[i].quaternion = Q_Axis(rotAxis_Tilt, infoList[i].tilt + noiseTilt) * init;
                        end = Quaternion.Slerp(tilt.localRotation, infoList[i].quaternion, infoList[i].weight / weight);
                        if (isDebugMode)
                        {
                            if(debugTilt)
                                tilt.localRotation = end;
                        }
                        else
                        {
                            tilt.localRotation = infoList[i].quaternion;
                        }
                        if (weight == 1)
                        {
                            previousLocalRot_Tilt = tilt.localRotation;
                            previousWorldRot_Tilt = tilt.rotation;
                        }
                    }
                }
            }
        }
        // Inspectorï¿½Å‘Iï¿½ñ‚¾ï¿½ï¿½ÆAï¿½pï¿½xï¿½Éï¿½ï¿½í‚¹ï¿½ï¿½Quaternionï¿½ï¿½Ô‚ï¿½
        Quaternion Q_Axis(Axis axis, float degree)
        {
            if (degree == 0)
                return Quaternion.identity;
            switch (axis)
            {
                default:
                    return Quaternion.Euler(Vector3.right * degree);
                case Axis.Y:
                    return Quaternion.Euler(Vector3.up * degree);
                case Axis.Z:
                    return Quaternion.Euler(Vector3.forward * degree);
            }
        }
        public enum Dir
        {
            UP,
            FORWARD
        }
        // Look At Targetï¿½pï¿½Ìï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½Tiltï¿½Wï¿½ï¿½
        Vector3 AxisAdjustTilt(Dir dir, int n, Transform t)
        {
            // Tilt: UPï¿½ï¿½6ï¿½ï¿½ï¿½
            switch (n)
            {
                default:
                    switch (dir) { default: return t.up;}
                case 1:
                    switch (dir) { default: return -t.up;}
                case 2:
                    switch (dir) { default: return t.right;}
                case 3:
                    switch (dir) { default: return -t.right;}
                case 4:
                    switch (dir) { default: return t.forward;}
                case 5:
                    switch (dir) { default: return -t.forward;}
            }
        }
        // Look At Targetï¿½pï¿½Ìï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½Panï¿½Wï¿½ï¿½
        Vector3 AxisAdjustPan(Dir dir, int n, Transform t)
        {
            // Pan: UPï¿½ï¿½3ï¿½ï¿½ŞAFORWARDï¿½ï¿½4ï¿½ï¿½ï¿½
            switch (n)
            {
                default:
                    switch (dir) { default: return t.up; case Dir.FORWARD: return t.forward;}
                case 1:
                    switch (dir) { default: return t.up; case Dir.FORWARD: return t.right;}
                case 2:
                    switch (dir) { default: return t.up; case Dir.FORWARD: return -t.forward;}
                case 3:
                    switch (dir) { default: return t.up; case Dir.FORWARD: return -t.right;}

                case 4:
                    switch (dir) { default: return t.right; case Dir.FORWARD: return t.up;}
                case 5:
                    switch (dir) { default: return t.right; case Dir.FORWARD: return t.forward;}
                case 6:
                    switch (dir) { default: return t.right; case Dir.FORWARD: return -t.up;}
                case 7:
                    switch (dir) { default: return t.right; case Dir.FORWARD: return -t.forward;}

                case 8:
                    switch (dir) { default: return t.forward; case Dir.FORWARD: return t.right;}
                case 9:
                    switch (dir) { default: return t.forward; case Dir.FORWARD: return t.up;}
                case 10:
                    switch (dir) { default: return t.forward; case Dir.FORWARD: return -t.right;}
                case 11:
                    switch (dir) { default: return t.forward; case Dir.FORWARD: return -t.up;}
            }
        }
        /// <summary>
        /// ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        /// </summary>
        Vector2 st = new Vector2();
        float RandomFloat(int seed)
        {
            st = new Vector2(seed, seed);
            return frac(Mathf.Sin(Vector2.Dot(st, new Vector2(12.9898f, 78.233f))) * 43758.5453f);
        }
        float frac(float f)
        {
            return f - Mathf.Floor(f);
        }
        Vector2 random2(Vector2 vec)
        {
            vec = new Vector2(Vector2.Dot(vec, new Vector2(127.1f, 311.7f)), Vector2.Dot(vec, new Vector2(269.5f, 183.3f)));
            var p = new Vector2(Mathf.Sin(vec.x), Mathf.Sin(vec.y)) * 43758.5453123f;
            var frac = p - new Vector2(Mathf.Floor(p.x), Mathf.Floor(p.y));
            return new Vector2(-1.0f, -1.0f) + 2.0f * frac;
        }
        float perlinNoise(Vector2 st)
        {
            Vector2 p = new Vector2(Mathf.Floor(st.x), Mathf.Floor(st.y));
            Vector2 f = st - p;
            Vector2 u = f * f * (new Vector2(3.0f, 3.0f) - 2.0f * f);

            float v00 = random2(p + new Vector2(0, 0)).x;
            float v10 = random2(p + new Vector2(1, 0)).x;
            float v01 = random2(p + new Vector2(0, 1)).x;
            float v11 = random2(p + new Vector2(1, 1)).x;

            return Mathf.Lerp(Mathf.Lerp(Vector2.Dot(new Vector2(v00, v00), f - new Vector2(0, 0)), Vector2.Dot(new Vector2(v10, v10), f - new Vector2(1, 0)), u.x),
                Mathf.Lerp(Vector2.Dot(new Vector2(v01, v01), f - new Vector2(0, 1)), Vector2.Dot(new Vector2(v11, v11), f - new Vector2(1, 1)), u.x), u.y) + 0.5f;
        }

    }
}
