using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;

/// <summary>
/// ï¿½ï¿½ï¿½Cï¿½gï¿½Ì‹ï¿½ï¿½ï¿½ï¿½Eï¿½Gï¿½~ï¿½bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Ì‹ï¿½ï¿½ï¿½ï¿½ÌŒWï¿½ï¿½ï¿½ï¿½Ûï¿½ï¿½ï¿½ï¿½ï¿½
/// Light Color Controllerï¿½ALight Emission Controllerï¿½Éˆêï¿½É‚Â‚ï¿½ï¿½Ä‚ï¿½ï¿½ÄAï¿½ï¿½ï¿½ï¿½ï¿½ÉQï¿½Æ‚ï¿½ï¿½ï¿½ï¿½B
/// Timelineï¿½Åï¿½ï¿½ä‚·ï¿½ï¿½pï¿½È‚Ì‚ÅAï¿½ï¿½ï¿½ä‚³ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ÍŒWï¿½ï¿½=1ï¿½ï¿½Ô‚ï¿½ï¿½Aï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½ï¿½Ü‚è‚µï¿½Ä‚Í‚ï¿½ï¿½ï¿½ï¿½È‚ï¿½
/// </summary>
namespace StudioMaron
{
    public class LightFlashController : MonoBehaviour, INotificationReceiver
    {
        // ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌQï¿½ÆBï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½Æ‚ï¿½ï¿½ï¿½Ì‚ï¿½Use Referenceï¿½ï¿½ï¿½[ï¿½hï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B
        LightColorController light_controller;
        EmissionColorController emission_controller;

        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½max60ï¿½É‚ï¿½ï¿½Ä•ï¿½ï¿½×‚ï¿½ï¿½ï¿½ï¿½ç‚·ï¿½pï¿½Ì•Ïï¿½
        float fps = 60;
        float deltaTime;
        int count;

        // Timelineï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ÌXï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
        bool parameterChangedByTimeline;

        // Markerï¿½ï¿½ï¿½ï¿½Ì’Ê’mï¿½Æ•Ïï¿½
        bool isMarkerControl;
        float markerControlIntensity;
        float markerControlDuration;
        float markerControlTime;

        // Light Flash Parameterï¿½Ìƒï¿½ï¿½Xï¿½g
        // Timelineï¿½ï¿½ï¿½ç‚±ï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½AUpdateï¿½ï¿½ï¿½ÉŒvï¿½Zï¿½ï¿½ï¿½ï¿½
        [HideInInspector] public List<LightFlashParameter> previousList = new List<LightFlashParameter>();

        // ï¿½vï¿½Zï¿½pï¿½Ì•Ïï¿½
        float m_Intensity;
        float m_Value;
        float m_CycleDuration;
        float m_CycleProgress;

        // ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½É•tï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ALight Color Controllerï¿½Ü‚ï¿½ï¿½ï¿½Light Emission Controllerï¿½ï¿½ï¿½æ“¾
        void Reset() 
        {
            light_controller = GetComponent<LightColorController>();
            if(light_controller == null)
                emission_controller = GetComponent<EmissionColorController>();
        }

        // Startï¿½ï¿½ï¿½ï¿½Light Color Parameterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½
        private void Start()
        {
            CreateParameter();
        }
        // ï¿½ï¿½ï¿½Light Color Parameterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½previousListï¿½É“ï¿½ï¿½ï¿½ï¿½
        void CreateParameter()
        {
            var param = new LightFlashParameter();
            param.flashBpm = 0;
            param.weight = 1;
            SetParameter(new List<LightFlashParameter>() { param });
        }
        // Light Flash Parameterï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½ì¬ï¿½ï¿½ï¿½ï¿½
        void SetParameter(List<LightFlashParameter> list)
        {
            previousList.Clear();
            previousList.AddRange(list);
        }

        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½g60(1.6msï¿½ï¿½ï¿½ï¿½)ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
        void Update()
        {
            // Markerï¿½É‚ï¿½é§ï¿½ï¿½Ìï¿½ï¿½ÔŒoï¿½ßï¿½ï¿½ï¿½
            if (0 < markerControlTime)
                markerControlTime -= Time.deltaTime;

            // Markerï¿½É‚ï¿½é§ï¿½ä‚ªï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½Oï¿½ï¿½falseï¿½É‚ï¿½ï¿½ï¿½
            if (markerControlTime < 0)
            {
                markerControlTime = 0;
                isMarkerControl = false;
            }

            // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½g60ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
            deltaTime += Time.deltaTime;
            if (deltaTime < 1 / fps) return;

            count = (int)(deltaTime * fps);
            deltaTime -= count / fps;

            // Timelineï¿½É‚ï¿½ï¿½ÏXï¿½ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Aï¿½Oï¿½ï¿½gï¿½ï¿½ï¿½ï¿½LightColorParameterï¿½Ì“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½iï¿½ß‚ÄÄ—ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½
            if (!parameterChangedByTimeline)
            {
                foreach (var o in previousList)
                    o.clipTime += count / fps;
            }
            parameterChangedByTimeline = false;
        }

        // ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ç”ï¿½lï¿½ï¿½ï¿½Qï¿½Æ‚ï¿½ï¿½ï¿½Öï¿½
        // Light Color Controllerï¿½Ü‚ï¿½ï¿½ï¿½Light Emission Controllerï¿½ï¿½ï¿½Aï¿½Nï¿½Zï¿½Xï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
        // isReferenceï¿½ï¿½Light Flash Controllerï¿½ï¿½ï¿½ï¿½Use Referenceï¿½ï¿½ï¿½[ï¿½hï¿½Å•Ê‚ï¿½Light Flash Controllerï¿½ï¿½ï¿½Qï¿½Æ‚ï¿½ï¿½ï¿½ê‡ï¿½É–ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½vï¿½ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ß‚Ìƒtï¿½ï¿½ï¿½O
        public float IntensityCoef(int n, int length, bool isReference = false)
        {
            // Markerï¿½É‚ï¿½éˆï¿½ï¿½ï¿½ï¿½ï¿½cï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½Aï¿½Êï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Markerï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Lerpï¿½Å•âŠ®ï¿½ï¿½ï¿½ï¿½
            if (isMarkerControl)
                return Mathf.Lerp(TimelineClipIntensity(n, length, isReference), MarkerIntensity(n, length), markerControlTime / markerControlDuration);
            else
                return TimelineClipIntensity(n, length, isReference);
        }
        // Markerï¿½É‚ï¿½ï¿½Wï¿½ï¿½ï¿½Zï¿½o
        float MarkerIntensity(int n, int length)
        {
            return markerControlIntensity * Mathf.Pow(markerControlTime / markerControlDuration, 4);
        }
        // Timeline clipï¿½É‚ï¿½ï¿½Wï¿½ï¿½ï¿½Zï¿½o
        float TimelineClipIntensity(int n, int length, bool isReference)
        {
            // ï¿½vï¿½Zï¿½pï¿½Ì•Ïï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
            m_Intensity = 0;

            // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½ÍŒWï¿½ï¿½ï¿½ï¿½1ï¿½ï¿½Ô‚ï¿½
            if (previousList.Count == 0)
                m_Intensity = 1;

            // ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½^ï¿½ï¿½ï¿½ÉŒWï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½Ä‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½
            for (int j = 0; j < previousList.Count; j++)
            {
                // ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½È‚çŸï¿½ï¿½
                if (previousList[j] == null) continue;

                // BPMï¿½ï¿½0ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
                if (previousList[j].flashBpm == 0)
                {
                    m_CycleDuration = 0;
                    m_CycleProgress = 0;
                    m_Value = previousList[j].timeAdjust;
                }
                else
                {
                    // BPMï¿½É‰ï¿½ï¿½ï¿½ï¿½Äiï¿½sï¿½x(0.0ï¿½`1.0)ï¿½ï¿½ï¿½vï¿½Z
                    m_CycleDuration = 60f * previousList[j].flashEveryBeatNumber / previousList[j].flashBpm;

                    if (m_CycleDuration == 0)
                        m_CycleProgress = 0;
                    else
                        m_CycleProgress = (previousList[j].clipTime % m_CycleDuration) / m_CycleDuration;

                    // m_Valueï¿½ï¿½BPMï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½sï¿½xï¿½ï¿½\ï¿½ï¿½
                    m_Value = previousList[j].timeAdjust + m_CycleProgress;
                }

                switch (previousList[j].flashMode)
                {
                    // Noneï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½weightï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ä•Ô‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
                    case LightFlashParameter.FlashMode.None:
                        m_Intensity += previousList[j].weight;
                        break;

                    // Allï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½Animation Curveï¿½ÌƒTï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Ä‘Sï¿½Ä‚Ìƒï¿½ï¿½Cï¿½gï¿½Å“ï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ 
                    case LightFlashParameter.FlashMode.All:
                        m_Value = frac(m_Value);
                        m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                        break;

                    // ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½hï¿½ï¿½Animation Curveï¿½ÌƒTï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½Æ‚Éï¿½ï¿½Ô‚É‚ï¿½ï¿½ç‚·
                    case LightFlashParameter.FlashMode.Line:
                        m_Value = frac(m_Value + 0.5f + (n + 0.5f) / length);
                        m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                        break;

                    // ï¿½Xï¿½Cï¿½bï¿½`ï¿½ï¿½ï¿½[ï¿½h
                    case LightFlashParameter.FlashMode.Switch:

                        // ï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô–Ú‚ÆŠï”ï¿½Ô–Ú‚Å•ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½İ‚É“_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                        if (m_CycleProgress < 0.5f)
                        {
                            if (n % 2 == 0)
                            {
                                m_Intensity += 0;
                            }
                            else
                            {
                                m_Value *= 2;
                                m_Value = frac(m_Value);
                                m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                            }
                        }
                        else
                        {
                            if (n % 2 == 0)
                            {
                                m_Value *= 2;
                                m_Value = frac(m_Value);
                                m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                            }
                            else
                            {
                                m_Intensity += 0;
                            }
                        }
                        break;

                    // ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½h
                    case LightFlashParameter.FlashMode.Split_3:

                        // ï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½3ï¿½Oï¿½ï¿½ï¿½[ï¿½vï¿½É•ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½Ô‚ï¿½ï¿½Æ‚ÉŒï¿½ï¿½ç‚¹ï¿½ï¿½Oï¿½ï¿½ï¿½[ï¿½vï¿½ï¿½Ï‚ï¿½ï¿½ï¿½
                        if (m_CycleProgress < 0.3333f)
                        {
                            if (RandomFloat(previousList[j].randomSeed + n) < 0.3333f)
                            {
                                m_Value *= 3;
                                m_Value = frac(m_Value);
                                m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                            }
                            else
                            {
                                m_Intensity += 0;
                            }
                        }
                        else if (m_CycleProgress < 0.6666f)
                        {
                            if (0.3333f <= RandomFloat(previousList[j].randomSeed + n) && RandomFloat(previousList[j].randomSeed + n) < 0.6666f)
                            {
                                m_Value *= 3;
                                m_Value = frac(m_Value);
                                m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                            }
                            else
                            {
                                m_Intensity += 0;
                            }
                        }
                        else
                        {
                            if (0.6666f <= RandomFloat(previousList[j].randomSeed + n) && RandomFloat(previousList[j].randomSeed + n) <= 1.0f)
                            {
                                m_Value *= 3;
                                m_Value = frac(m_Value);
                                m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                            }
                            else
                            {
                                m_Intensity += 0;
                            }
                        }
                        break;

                    // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Xï¿½Cï¿½bï¿½`ï¿½ï¿½ï¿½[ï¿½h
                    case LightFlashParameter.FlashMode.RandomSwitch:

                        // Random Seedï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Ä‹^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                        m_Value = frac(m_Value + RandomFloat(previousList[j].randomSeed + n));

                        // m_Valurï¿½ï¿½ï¿½ï¿½ï¿½È‰ï¿½ï¿½Ìƒï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ç‚¹ï¿½ï¿½Bm_Valueï¿½É‚Íï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ì‚ÅAï¿½ï¿½ï¿½ÔŒoï¿½ß‚ÅŒï¿½ï¿½éƒ‰ï¿½Cï¿½gï¿½ï¿½ï¿½Ï‚ï¿½ï¿½
                        if (m_Value < previousList[j].randomSwitchRate)
                        {
                            // Random Switch Rateï¿½ÅŒï¿½ï¿½ç‚¹ï¿½éŠ„ï¿½ï¿½ï¿½ğ’²ï¿½
                            m_Value *= 1 / previousList[j].randomSwitchRate;

                            // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½Ì‚İï¿½ï¿½oï¿½ï¿½
                            m_Value = frac(m_Value);

                            // m_Valueï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½Animation Curveï¿½ï¿½ï¿½ç”ï¿½lï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
                            m_Intensity += previousList[j].flashCurve.Evaluate(m_Value) * previousList[j].weight;
                        }
                        else
                        {
                            m_Intensity += 0;
                        }
                        break;

                    // Referenceï¿½ï¿½ï¿½Qï¿½Æ‚ï¿½ï¿½éƒ‚ï¿½[ï¿½h
                    case LightFlashParameter.FlashMode.UseReference:
                        
                        // ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ê‡ï¿½Íæ“¾ï¿½ï¿½ï¿½ï¿½ï¿½İ‚ï¿½
                        if(light_controller == null && emission_controller == null)
                        {
                            light_controller = GetComponent<LightColorController>();
                            if (light_controller == null)
                                emission_controller = GetComponent<EmissionColorController>();
                        }
                        // Light Color Controllerï¿½ï¿½Referenceï¿½ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½ï¿½Referenceï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½æ“¾
                        if (light_controller != null)
                        {
                            if (light_controller.reference != null)
                                if (!isReference) // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½vï¿½hï¿½~
                                    m_Intensity += light_controller.reference.GetReferenceFlashCoef(n, length);
                        }
                        // Light Emission Controllerï¿½ï¿½Referenceï¿½ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½Aï¿½ï¿½ï¿½ï¿½Referenceï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½æ“¾
                        else if (emission_controller != null)
                        {
                            if (emission_controller.reference != null)
                                if (!isReference) // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½vï¿½hï¿½~
                                    m_Intensity += emission_controller.reference.GetReferenceFlashCoef(n, length);
                        }
                        break;
                }
            }
            return m_Intensity;
        }

        // Timeline clipï¿½ï¿½ï¿½ç”­ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
        public void SetParameterFromTimeline(List<LightFlashParameter> parameter)
        {
#if UNITY_EDITOR
            if (UnityEditor.EditorApplication.isPlaying)
            {
                SetParameter(parameter);
            }
            else
            {
                SetParameter(parameter);
            }
#else
                SetParameter(parameter);
#endif
            // Timelineï¿½É‚ï¿½ï¿½Xï¿½Vï¿½tï¿½ï¿½ï¿½O
            parameterChangedByTimeline = true;
        }

       // Timelineï¿½Ìƒvï¿½ï¿½ï¿½rï¿½ï¿½ï¿½[ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        public void ReapplyParameter()
        {
#if UNITY_EDITOR
            if (!UnityEditor.EditorApplication.isPlaying)
            {
                CreateParameter();
            }
#endif
        }

        // ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
        Vector2 st = new Vector2();
        float RandomFloat(int seed)
        {
            st = new Vector2(seed, seed);
            return frac(Mathf.Sin(Vector2.Dot(st, new Vector2(12.9898f, 78.233f))) * 43758.5453f);
        }
        float frac(float f)
        {
            return f - Mathf.Floor(f);
        }

        // Markerï¿½Ê‚Ì”ï¿½ï¿½ï¿½
        public void OnNotify(Playable origin, INotification notification, object context)
        {
            // Light Flash Markerï¿½Ì‚İ”ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            if (!(notification is LightFlashMarker)) return;

            var marker = notification as LightFlashMarker;

            // ï¿½è“®ï¿½ï¿½Timelineï¿½ÌƒVï¿½[ï¿½Nï¿½oï¿½[ï¿½ğ“®‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É”ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½éˆï¿½ï¿½
            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½ï¿½Markerï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î‚ï¿½ï¿½Â”\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½é‚±ï¿½Æ‚É’ï¿½ï¿½ï¿½
            if (!(origin.GetTime() < marker.time + 0.1f)) return;

            // ï¿½tï¿½ï¿½ï¿½bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            LightFlash_Flash(marker.flashIntensity, marker.flashTime);
        }

        // Markerï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½lï¿½ï¿½ï¿½ï¿½Ïï¿½ï¿½ÉŠiï¿½[
        void LightFlash_Flash(float intensity, float time)
        {
            isMarkerControl = true;
            markerControlIntensity = intensity;
            markerControlDuration = time;
            markerControlTime = time;
        }
    }
}
